/**
 * Client-side Kipit-branded statement / document export (browser view + download).
 * Used where kipit-api has no statements PDF endpoint yet.
 */

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildHtml(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
}) {
  const rowsHtml = (input.rows ?? [])
    .map(
      (r) =>
        `<tr>
          <td style="padding:10px 8px;border-bottom:1px solid #e2e8f0;color:#64748b;font-size:12px;vertical-align:top;width:55%">${escapeHtml(r.label)}</td>
          <td style="padding:10px 8px;border-bottom:1px solid #e2e8f0;text-align:right;font-weight:600;font-size:13px;vertical-align:top;font-family:system-ui,sans-serif">${escapeHtml(r.value)}</td>
        </tr>`,
    )
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${escapeHtml(input.title)}</title></head>
<body style="font-family:Georgia,'Times New Roman',serif;padding:28px;color:#0f172a;max-width:720px;margin:0 auto;background:#fff">
  <div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#b45309;font-weight:700">Kipit</div>
  <h1 style="margin:12px 0 4px;font-size:22px;font-family:system-ui,sans-serif">${escapeHtml(input.title)}</h1>
  ${input.subtitle ? `<p style="margin:0 0 20px;color:#64748b;font-size:13px">${escapeHtml(input.subtitle)}</p>` : ""}
  ${
    rowsHtml
      ? `<table style="width:100%;border-collapse:collapse;margin-top:8px">
          <thead>
            <tr>
              <th style="text-align:left;padding:8px;border-bottom:2px solid #cbd5e1;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#94a3b8">Detail</th>
              <th style="text-align:right;padding:8px;border-bottom:2px solid #cbd5e1;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#94a3b8">Value</th>
            </tr>
          </thead>
          <tbody>${rowsHtml}</tbody>
        </table>`
      : `<p style="margin-top:24px;color:#64748b;font-size:13px">No rows to display for this period.</p>`
  }
  ${input.body ? `<p style="margin-top:24px;line-height:1.5;font-size:13px;color:#334155">${escapeHtml(input.body)}</p>` : ""}
  <p style="margin-top:40px;font-size:11px;color:#94a3b8">Generated by Kipit · ${escapeHtml(new Date().toLocaleString("en-NG"))}</p>
</body></html>`;
}

/** Open a Kipit-branded document in a new tab for viewing (no print dialog). */
export function openDocumentHtml(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
}): { opened: boolean; url: string; html: string } {
  const html = buildHtml(input);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, "_blank", "noopener,noreferrer");
  if (w) {
    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
    return { opened: true, url, html };
  }
  // Caller can show an in-app viewer with `html` when pop-ups are blocked.
  window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
  return { opened: false, url, html };
}

/** Open the system print dialog with a Kipit-branded document. */
export function printDocumentPdf(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
}) {
  const html = buildHtml(input);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, "_blank", "noopener,noreferrer");
  if (!w) {
    URL.revokeObjectURL(url);
    throw new Error("Pop-up blocked — allow pop-ups to print this document.");
  }
  window.setTimeout(() => {
    try {
      w.focus();
      w.print();
    } catch {
      /* user can print manually */
    }
    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
  }, 400);
}

/** HTML string for a Kipit-branded document (also used for server email attach). */
export function documentHtml(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
}) {
  return buildHtml(input);
}

/** Download an HTML document the user can open or print to PDF. */
export function downloadDocumentPdf(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
  filename?: string;
}) {
  const html = buildHtml(input);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = input.filename ?? `${input.title.replace(/\s+/g, "-").toLowerCase()}.html`;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Keep the blob alive long enough for staggered multi-file downloads.
  window.setTimeout(() => URL.revokeObjectURL(url), 10_000);
}
