/**
 * Client-side Kipit-branded statement / document export (browser print + download).
 * Used where kipit-api has no statements PDF endpoint yet.
 */

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildHtml(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
}) {
  const rowsHtml = (input.rows ?? [])
    .map(
      (r) =>
        `<tr><td style="padding:8px 0;color:#64748b;font-size:12px">${escapeHtml(r.label)}</td><td style="padding:8px 0;text-align:right;font-weight:600;font-size:13px">${escapeHtml(r.value)}</td></tr>`,
    )
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${escapeHtml(input.title)}</title></head>
<body style="font-family:Georgia,'Times New Roman',serif;padding:32px;color:#0f172a;max-width:640px;margin:0 auto">
  <div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#b45309;font-weight:700">Kipit</div>
  <h1 style="margin:12px 0 4px;font-size:22px;font-family:system-ui,sans-serif">${escapeHtml(input.title)}</h1>
  ${input.subtitle ? `<p style="margin:0 0 20px;color:#64748b;font-size:13px">${escapeHtml(input.subtitle)}</p>` : ""}
  ${rowsHtml ? `<table style="width:100%;border-collapse:collapse;margin-top:8px">${rowsHtml}</table>` : ""}
  ${input.body ? `<p style="margin-top:24px;line-height:1.5;font-size:13px;color:#334155">${escapeHtml(input.body)}</p>` : ""}
  <p style="margin-top:40px;font-size:11px;color:#94a3b8">Generated by Kipit · ${escapeHtml(new Date().toLocaleString("en-NG"))}</p>
</body></html>`;
}

/** Open the system print dialog with a Kipit-branded document. */
export function printDocumentPdf(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
}) {
  const html = buildHtml(input);
  const w = window.open("", "_blank", "noopener,noreferrer,width=720,height=900");
  if (!w) throw new Error("Pop-up blocked — allow pop-ups to view or print this document.");
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  window.setTimeout(() => {
    try {
      w.print();
    } catch {
      /* user can print manually */
    }
  }, 250);
}

/** HTML string for a Kipit-branded document (also used for server email attach). */
export function documentHtml(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
}) {
  return buildHtml(input);
}

/** Download an HTML document the user can open or print to PDF. */
export function downloadDocumentPdf(input: {
  title: string;
  subtitle?: string;
  rows?: { label: string; value: string }[];
  body?: string;
  filename?: string;
}) {
  const html = buildHtml(input);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = input.filename ?? `${input.title.replace(/\s+/g, "-").toLowerCase()}.html`;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 2_000);
}
