/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallAccountRouteImport } from './routes/call-account'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FixedPlansRouteImport } from './routes/fixed-plans'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CallAccountAddMoneyRouteImport } from './routes/call-account_.add-money'
import { Route as CallAccountReviewRouteImport } from './routes/call-account_.review'
import { Route as CallAccountSuccessRouteImport } from './routes/call-account_.success'
import { Route as FixedPlansCreateRouteImport } from './routes/fixed-plans_/create'
import { Route as FixedPlansCreateIndexRouteImport } from './routes/fixed-plans_/create/index'
import { Route as FixedPlansCreateOptionsRouteImport } from './routes/fixed-plans_/create/options'
import { Route as FixedPlansCreateTenorRouteImport } from './routes/fixed-plans_/create/tenor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallAccountRoute = CallAccountRouteImport.update({
  id: '/call-account',
  path: '/call-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedPlansRoute = FixedPlansRouteImport.update({
  id: '/fixed-plans',
  path: '/fixed-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CallAccountAddMoneyRoute = CallAccountAddMoneyRouteImport.update({
  id: '/call-account_/add-money',
  path: '/call-account/add-money',
  getParentRoute: () => rootRouteImport,
} as any)
const CallAccountReviewRoute = CallAccountReviewRouteImport.update({
  id: '/call-account_/review',
  path: '/call-account/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CallAccountSuccessRoute = CallAccountSuccessRouteImport.update({
  id: '/call-account_/success',
  path: '/call-account/success',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedPlansCreateRoute = FixedPlansCreateRouteImport.update({
  id: '/fixed-plans_/create',
  path: '/fixed-plans/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedPlansCreateIndexRoute = FixedPlansCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FixedPlansCreateRoute,
} as any)
const FixedPlansCreateOptionsRoute = FixedPlansCreateOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => FixedPlansCreateRoute,
} as any)
const FixedPlansCreateTenorRoute = FixedPlansCreateTenorRouteImport.update({
  id: '/tenor',
  path: '/tenor',
  getParentRoute: () => FixedPlansCreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call-account': typeof CallAccountRoute
  '/explore': typeof ExploreRoute
  '/fixed-plans': typeof FixedPlansRoute
  '/invest': typeof InvestRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/call-account/add-money': typeof CallAccountAddMoneyRoute
  '/call-account/review': typeof CallAccountReviewRoute
  '/call-account/success': typeof CallAccountSuccessRoute
  '/fixed-plans/create': typeof FixedPlansCreateRouteWithChildren
  '/fixed-plans/create/options': typeof FixedPlansCreateOptionsRoute
  '/fixed-plans/create/tenor': typeof FixedPlansCreateTenorRoute
  '/fixed-plans/create/': typeof FixedPlansCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call-account': typeof CallAccountRoute
  '/explore': typeof ExploreRoute
  '/fixed-plans': typeof FixedPlansRoute
  '/invest': typeof InvestRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/call-account/add-money': typeof CallAccountAddMoneyRoute
  '/call-account/review': typeof CallAccountReviewRoute
  '/call-account/success': typeof CallAccountSuccessRoute
  '/fixed-plans/create/options': typeof FixedPlansCreateOptionsRoute
  '/fixed-plans/create/tenor': typeof FixedPlansCreateTenorRoute
  '/fixed-plans/create': typeof FixedPlansCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call-account': typeof CallAccountRoute
  '/explore': typeof ExploreRoute
  '/fixed-plans': typeof FixedPlansRoute
  '/invest': typeof InvestRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/call-account_/add-money': typeof CallAccountAddMoneyRoute
  '/call-account_/review': typeof CallAccountReviewRoute
  '/call-account_/success': typeof CallAccountSuccessRoute
  '/fixed-plans_/create': typeof FixedPlansCreateRouteWithChildren
  '/fixed-plans_/create/options': typeof FixedPlansCreateOptionsRoute
  '/fixed-plans_/create/tenor': typeof FixedPlansCreateTenorRoute
  '/fixed-plans_/create/': typeof FixedPlansCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call-account'
    | '/explore'
    | '/fixed-plans'
    | '/invest'
    | '/notifications'
    | '/portfolio'
    | '/settings'
    | '/call-account/add-money'
    | '/call-account/review'
    | '/call-account/success'
    | '/fixed-plans/create'
    | '/fixed-plans/create/options'
    | '/fixed-plans/create/tenor'
    | '/fixed-plans/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call-account'
    | '/explore'
    | '/fixed-plans'
    | '/invest'
    | '/notifications'
    | '/portfolio'
    | '/settings'
    | '/call-account/add-money'
    | '/call-account/review'
    | '/call-account/success'
    | '/fixed-plans/create/options'
    | '/fixed-plans/create/tenor'
    | '/fixed-plans/create'
  id:
    | '__root__'
    | '/'
    | '/call-account'
    | '/explore'
    | '/fixed-plans'
    | '/invest'
    | '/notifications'
    | '/portfolio'
    | '/settings'
    | '/call-account_/add-money'
    | '/call-account_/review'
    | '/call-account_/success'
    | '/fixed-plans_/create'
    | '/fixed-plans_/create/options'
    | '/fixed-plans_/create/tenor'
    | '/fixed-plans_/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallAccountRoute: typeof CallAccountRoute
  ExploreRoute: typeof ExploreRoute
  FixedPlansRoute: typeof FixedPlansRoute
  InvestRoute: typeof InvestRoute
  NotificationsRoute: typeof NotificationsRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  CallAccountAddMoneyRoute: typeof CallAccountAddMoneyRoute
  CallAccountReviewRoute: typeof CallAccountReviewRoute
  CallAccountSuccessRoute: typeof CallAccountSuccessRoute
  FixedPlansCreateRoute: typeof FixedPlansCreateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-account': {
      id: '/call-account'
      path: '/call-account'
      fullPath: '/call-account'
      preLoaderRoute: typeof CallAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-plans': {
      id: '/fixed-plans'
      path: '/fixed-plans'
      fullPath: '/fixed-plans'
      preLoaderRoute: typeof FixedPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-account_/add-money': {
      id: '/call-account_/add-money'
      path: '/call-account/add-money'
      fullPath: '/call-account/add-money'
      preLoaderRoute: typeof CallAccountAddMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-account_/review': {
      id: '/call-account_/review'
      path: '/call-account/review'
      fullPath: '/call-account/review'
      preLoaderRoute: typeof CallAccountReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-account_/success': {
      id: '/call-account_/success'
      path: '/call-account/success'
      fullPath: '/call-account/success'
      preLoaderRoute: typeof CallAccountSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-plans_/create': {
      id: '/fixed-plans_/create'
      path: '/fixed-plans/create'
      fullPath: '/fixed-plans/create'
      preLoaderRoute: typeof FixedPlansCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-plans_/create/': {
      id: '/fixed-plans_/create/'
      path: '/'
      fullPath: '/fixed-plans/create/'
      preLoaderRoute: typeof FixedPlansCreateIndexRouteImport
      parentRoute: typeof FixedPlansCreateRoute
    }
    '/fixed-plans_/create/options': {
      id: '/fixed-plans_/create/options'
      path: '/options'
      fullPath: '/fixed-plans/create/options'
      preLoaderRoute: typeof FixedPlansCreateOptionsRouteImport
      parentRoute: typeof FixedPlansCreateRoute
    }
    '/fixed-plans_/create/tenor': {
      id: '/fixed-plans_/create/tenor'
      path: '/tenor'
      fullPath: '/fixed-plans/create/tenor'
      preLoaderRoute: typeof FixedPlansCreateTenorRouteImport
      parentRoute: typeof FixedPlansCreateRoute
    }
  }
}

interface FixedPlansCreateRouteChildren {
  FixedPlansCreateOptionsRoute: typeof FixedPlansCreateOptionsRoute
  FixedPlansCreateTenorRoute: typeof FixedPlansCreateTenorRoute
  FixedPlansCreateIndexRoute: typeof FixedPlansCreateIndexRoute
}

const FixedPlansCreateRouteChildren: FixedPlansCreateRouteChildren = {
  FixedPlansCreateOptionsRoute: FixedPlansCreateOptionsRoute,
  FixedPlansCreateTenorRoute: FixedPlansCreateTenorRoute,
  FixedPlansCreateIndexRoute: FixedPlansCreateIndexRoute,
}

const FixedPlansCreateRouteWithChildren =
  FixedPlansCreateRoute._addFileChildren(FixedPlansCreateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallAccountRoute: CallAccountRoute,
  ExploreRoute: ExploreRoute,
  FixedPlansRoute: FixedPlansRoute,
  InvestRoute: InvestRoute,
  NotificationsRoute: NotificationsRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  CallAccountAddMoneyRoute: CallAccountAddMoneyRoute,
  CallAccountReviewRoute: CallAccountReviewRoute,
  CallAccountSuccessRoute: CallAccountSuccessRoute,
  FixedPlansCreateRoute: FixedPlansCreateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
